### ISSUE TITLE
Create events page

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#123]
**The event specific page is a different task ( #270 ) **
```[tasklist]
### Tasks
- [x] Create event card
- [x] Display all events card
- [x] Sort based on date
- [x] Don't show events that have ended
```
