### ISSUE TITLE
Allow users to give their attendance on a event

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#126]
```[tasklist]
### Must be completed first
- [ ] #270 
```

![Image](https://github.com/ASVGay/the-rhapsodies/assets/54884540/dcb9563f-14d8-43ef-a88b-678e67b4c0ac)

```[tasklist]
### Tasks
- [x] Show toast on submitting presence
- [x] Highlight current presence
- [x] Presence set by default to undecided
```
