### ISSUE TITLE
Create event as admin

### ISSUE THREAD

**Issue by rensdoodeman** [ASVGay/the-rhapsodies#260]
```[tasklist]
### Must be completed first
- [ ] #123 
```

```[tasklist]
### Tasks
- [x] Add plus button
- [x] Create event form
- [x] Show toast on error/succes
- [x] On success redirect to new event
```
