### ISSUE TITLE
Create presence box

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#269]
Another issue has been created for remarks #274 

```[tasklist]
### Tasks
- [x] Show names by each status
- [x] Show 'No members have marked themselves [STATUS]' if there are no members with that status
- [x] Highlight name of logged in user
- [x] Show present by default
```

![Image](https://github.com/ASVGay/the-rhapsodies/assets/54884540/d37f69c8-ff99-45e5-8559-64469efad182)
