### ISSUE TITLE
Create event specific page

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#270]
```[tasklist]
### Tasks
- [x] Show event info
- [x] Add close button -> redirects to events
- [x] route = events/[id]
```

**Submitting presence #126 & showing presence #269  are in other issues**
