### ISSUE TITLE
Allow admins to delete an event

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#272]
```[tasklist]
### Must be completed first
- [ ] #270 
- [ ] #260 
```
```[tasklist]
### Tasks
- [ ] Create delete modal
- [ ] Show confirm text if clicked on I want to delete this event
- [ ] Disable button without text input
- [ ] Show toast on error/success of deletion
```
