### ISSUE TITLE
Allow admins to edit an event

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#273]
```[tasklist]
### Must be completed first
- [ ] #270 
- [ ] #260 
```

```[tasklist]
### Tasks
- [x] Get the values of the event
- [x] Update values (and validate) on submit
- [x] Show toast on success & error
- [x] Redirect to event on close & successful submit
```
