### ISSUE TITLE
Allow users to add a remark to their presence

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#274]
```[tasklist]
### Must be completed first
- [ ]  #126 
- [x] #269 
```

```[tasklist]
### Tasks
- [x] Show remark text area
- [x] Prevent users from saving empty remark
- [ ] Show delete button if text is set
- [x] Show remark in presence block
```
